services:
  app:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: ["rye", "run", "streamlit", "run", "src/streamlit_starter_kit/app.py", "--server.address=0.0.0.0", "--server.enableXsrfProtection=false", "--server.enableCORS=false"]
    networks:
      - streamlit_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - streamlit_network

networks:
  streamlit_network:
    driver: bridge
